# Generated by Django 4.2.2 on 2023-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsstory_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='udpate_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
