# Generated by Django 4.2.2 on 2023-07-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsstory_udpate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='udpate_date',
            new_name='update_date',
        ),
    ]
