# Generated by Django 4.2.2 on 2023-07-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_udpate_date_newsstory_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='update_date',
        ),
    ]
